-- migrate:up
ALTER TABLE riders
MODIFY data_1 DECIMAL(3,1) NULL DEFAULT 0,
MODIFY data_2 DECIMAL(3,1) NULL DEFAULT 0,
MODIFY data_3 DECIMAL(3,1) NULL DEFAULT 0,
MODIFY data_4 DECIMAL(3,1) NULL DEFAULT 0,
MODIFY data_5 DECIMAL(3,1) NULL DEFAULT 0,
MODIFY data_6 DECIMAL(3,1) NULL DEFAULT 0,
MODIFY safe_score DECIMAL(4,1) NULL DEFAULT 0;

-- migrate:down
DROP TABLE riders;