-- migrate:up
CREATE TABLE riders(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    data_1 DECIMAL(3,1) NOT NULL DEFAULT 0,
    data_2 DECIMAL(3,1) NOT NULL DEFAULT 0,
    data_3 DECIMAL(3,1) NOT NULL DEFAULT 0,
    data_4 DECIMAL(3,1) NOT NULL DEFAULT 0,
    data_5 DECIMAL(3,1) NOT NULL DEFAULT 0,
    data_6 DECIMAL(3,1) NOT NULL DEFAULT 0,
    safe_score DECIMAL(4,1) NOT NULL DEFAULT 0,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- migrate:down
DROP TABLE riders;
